# version: '3.8'
# services:
#   stackunderflow:
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
#       SPRING_DATASOURCE_USERNAME: pavan
#       SPRING_DATASOURCE_PASSWORD: pavan
#     depends_on:
#       - mysql
#   mysql:
#     image: mysql:5.7
#     environment:
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#       MYSQL_ROOT_PASSWORD: password
#     volumes:
#       - mysql-data:/var/lib/mysql

# volumes:
#   mysql-data:
